### PR TITLE
Dev startup fixes (Mac os)

### PR DESCRIPTION
**Pull request by shadrach-tayo**
## Changes
- Upgrade desci-server node version
- Upgrade dev startup script to use `apt-get install`

### CODE REVIEW

**Comment by hubsmoke** [comment]
I have no issues starting the dev service on mac without these changes, just using what's on develop @shadrach-tayo

**Comment by m0ar** [comment]
Also not sure what's the actual issue at play here, but also don't see any harm in changing the base image a couple of minors I guess :shrug:

**Review by m0ar — APPROVED** [review]

**Comment by m0ar** [comment]
Running some services on bookworm and some on bullseye might be a bit unnecessary though, is that required or is the node version bump enough?

**Comment by shadrach-tayo** [comment]
> Running some services on bookworm and some on bullseye might be a bit unnecessary though, is that required or is the node version bump enough?

the bookworm image is broken for me 
Screenshot 2024-04-09 at 11 58 38
Screenshot 2024-04-09 at 12 00 28

changing it back to bullseyes fixes it

**Comment by shadrach-tayo** [comment]
Either way I'm closing this PR because the relevant fixes here are in from the [Highlight PR](https://github.com/desci-labs/nodes/pull/264)

**Pull request closed without merging**
